# ============================================================
# EvalLab - Client Provisioning Script
# Run this once per new client deployment.
# ============================================================

Write-Host ""
Write-Host "=================================================" -ForegroundColor Green
Write-Host "  EvalLab Client Provisioning Script" -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Green
Write-Host ""

# 1. Collect client details
$ClientName    = Read-Host "Client business name (e.g. Smith and Co Estate Agents)"
$ClientSlug    = Read-Host "Short slug - no spaces (e.g. smithco)"
$ClientDomain  = Read-Host "Client website domain (e.g. smithco.co.uk)"
$VercelUrl     = Read-Host "Vercel deployment URL (e.g. https://smithco-evallab.vercel.app)"

Write-Host ""
Write-Host "-- Supabase credentials --" -ForegroundColor Cyan
$SupabaseUrl      = Read-Host "NEXT_PUBLIC_SUPABASE_URL"
$SupabaseAnonKey  = Read-Host "NEXT_PUBLIC_SUPABASE_ANON_KEY"
$SupabaseRoleKey  = Read-Host "SUPABASE_SERVICE_ROLE_KEY"

Write-Host ""
Write-Host "-- OpenAI credentials --" -ForegroundColor Cyan
$OpenAIKey = Read-Host "OPENAI_API_KEY"

Write-Host ""
Write-Host "-- Langfuse credentials (press Enter to skip) --" -ForegroundColor Cyan
$LangfusePublic  = Read-Host "LANGFUSE_PUBLIC_KEY"
$LangfuseSecret  = Read-Host "LANGFUSE_SECRET_KEY"
$LangfuseHost    = Read-Host "LANGFUSE_HOST (press Enter for https://cloud.langfuse.com)"
if ([string]::IsNullOrWhiteSpace($LangfuseHost)) {
    $LangfuseHost = "https://cloud.langfuse.com"
}

Write-Host ""
Write-Host "Confirm the following:" -ForegroundColor Yellow
Write-Host "  Client name : $ClientName"
Write-Host "  Slug        : $ClientSlug"
Write-Host "  Domain      : $ClientDomain"
Write-Host "  Vercel URL  : $VercelUrl"
Write-Host ""
$Confirm = Read-Host "Proceed? (y/n)"
if ($Confirm -ne "y") {
    Write-Host "Aborted." -ForegroundColor Red
    exit 1
}

# 2. Branding find-and-replace
# IMPORTANT: word-boundary safe. "EvalLab" will NOT match inside
# RetrievalLabPage, EvalLabConfig, evallab.au, etc. Only matches
# EvalLab as a standalone identifier/word, plus a hardcoded fix
# for the one known JS-identifier case (window.EvalLabConfig).
Write-Host ""
Write-Host "Replacing branding..." -ForegroundColor Cyan

$Extensions = @("*.tsx", "*.ts", "*.css", "*.json", "*.md", "*.html", "*.js", "*.mjs")

# Files to skip entirely - templates and the script itself, not branded UI.
$ExcludeFiles = @(
    "setup-client.ps1",
    "CLIENT_ONBOARDING.md"
)

# Word-boundary replacements. \b on both sides means "EvalLab" only matches
# when it is NOT glued to other letters (so RetrievalLabPage is untouched).
$WordBoundaryReplacements = @(
    @{ From = "\bEvalLab\b"; To = $ClientName },
    @{ From = "\bevallab\b"; To = $ClientSlug },
    @{ From = "AI Knowledge Base Evaluation Platform"; To = "$ClientName AI Knowledge Base" },
    @{ From = "RAG Evaluation Platform"; To = "AI Knowledge Base" },
    @{ From = "ai-eval-platform"; To = "$ClientSlug-evallab" }
)

# Exact, literal replacements for known JS-identifier lines that must stay
# syntactically valid (these are NOT regex - exact string match only).
$LiteralReplacements = @(
    @{ From = "window.EvalLabConfig"; To = "window.EvalLabConfig" }
)

$FilesChanged = 0

foreach ($ext in $Extensions) {
    $files = Get-ChildItem -Recurse -Filter $ext -ErrorAction SilentlyContinue |
             Where-Object {
                 $_.FullName -notmatch "node_modules|\.next|\.git" -and
                 ($ExcludeFiles -notcontains $_.Name)
             }

    foreach ($file in $files) {
        $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
        if ($null -eq $content) { continue }

        $original = $content

        foreach ($r in $WordBoundaryReplacements) {
            $content = [regex]::Replace($content, $r.From, { param($m) $r.To })
        }

        if ($content -ne $original) {
            Set-Content -Path $file.FullName -Value $content -NoNewline
            Write-Host "  Updated: $($file.FullName)" -ForegroundColor Gray
            $FilesChanged++
        }
    }
}

Write-Host "  $FilesChanged file(s) updated." -ForegroundColor Green
Write-Host "  (CLIENT_ONBOARDING.md and setup-client.ps1 were skipped - templates, not UI.)" -ForegroundColor DarkGray

# 3. Generate .env.local
Write-Host ""
Write-Host "Generating .env.local..." -ForegroundColor Cyan

$date = Get-Date -Format "yyyy-MM-dd HH:mm"
$envLines = @(
    "# ============================================================",
    "# $ClientName - EvalLab Environment Configuration",
    "# Generated by setup-client.ps1 on $date",
    "# ============================================================",
    "",
    "# Supabase",
    "NEXT_PUBLIC_SUPABASE_URL=$SupabaseUrl",
    "NEXT_PUBLIC_SUPABASE_ANON_KEY=$SupabaseAnonKey",
    "SUPABASE_SERVICE_ROLE_KEY=$SupabaseRoleKey",
    "",
    "# OpenAI",
    "OPENAI_API_KEY=$OpenAIKey",
    "",
    "# Langfuse observability",
    "LANGFUSE_PUBLIC_KEY=$LangfusePublic",
    "LANGFUSE_SECRET_KEY=$LangfuseSecret",
    "LANGFUSE_HOST=$LangfuseHost",
    "LANGFUSE_BASEURL=$LangfuseHost"
)

$envLines | Set-Content -Path ".env.local"
Write-Host "  .env.local written." -ForegroundColor Green

# 4. Print manual steps
Write-Host ""
Write-Host "=================================================" -ForegroundColor Yellow
Write-Host "  MANUAL STEPS REQUIRED" -ForegroundColor Yellow
Write-Host "=================================================" -ForegroundColor Yellow
Write-Host ""
Write-Host "0. VERCEL - import the repo and ADD ENV VARS FIRST," -ForegroundColor White
Write-Host "   then deploy. Do not deploy before env vars are set." -ForegroundColor Gray
Write-Host ""
Write-Host "1. SUPABASE SQL EDITOR - run supabase/schema.sql" -ForegroundColor White
Write-Host "   This creates all tables, RLS, RPCs and indexes." -ForegroundColor Gray
Write-Host ""
Write-Host "2. SUPABASE AUTH - set these URLs:" -ForegroundColor White
Write-Host "   Site URL    : $VercelUrl" -ForegroundColor Cyan
Write-Host "   Redirect URL: $VercelUrl/auth/callback" -ForegroundColor Cyan
Write-Host ""
Write-Host "3. CREATE CLIENT USER in Supabase Auth:" -ForegroundColor White
Write-Host "   Authentication > Users > Add user" -ForegroundColor Cyan
Write-Host ""
Write-Host "4. VERCEL ENV VARS - copy every line from .env.local into" -ForegroundColor White
Write-Host "   Settings > Environment Variables (before first deploy)" -ForegroundColor Cyan
Write-Host ""
Write-Host "5. DEPLOY:" -ForegroundColor White
Write-Host "   git add -A" -ForegroundColor Cyan
Write-Host "   git commit -m `"Client: $ClientName provisioning`"" -ForegroundColor Cyan
Write-Host "   git push origin main" -ForegroundColor Cyan
Write-Host ""
Write-Host "6. LOG IN to the deployed site and click 'Generate API Key'" -ForegroundColor White
Write-Host "   on the Deploy page - this does NOT happen automatically." -ForegroundColor Gray
Write-Host ""
Write-Host "7. WARM-UP NOTE: a brand new Vercel + Supabase pairing can" -ForegroundColor White
Write-Host "   take up to an hour to fully connect on first use. If the" -ForegroundColor Gray
Write-Host "   public chatbot 401s or times out immediately after deploy," -ForegroundColor Gray
Write-Host "   wait and retry before debugging further." -ForegroundColor Gray
Write-Host ""
Write-Host "=================================================" -ForegroundColor Green
Write-Host "  Provisioning complete for: $ClientName" -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Green
Write-Host ""
