# ============================================================
# EvalLab — Client Provisioning Script
# Run this once per new client deployment.
# It renames all branding, generates a fresh .env.local,
# and prints the Supabase setup checklist.
# ============================================================

Write-Host ""
Write-Host "=================================================" -ForegroundColor Green
Write-Host "  EvalLab Client Provisioning Script" -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Green
Write-Host "" 

0. CLEAN DATABASE — run in Supabase SQL Editor:
   TRUNCATE TABLE public.evaluation_logs, public.experiment_runs, public.semantic_cache CASCADE;

# ── 1. Collect client details ────────────────────────────────
$ClientName    = Read-Host "Client business name (e.g. Smith & Co Estate Agents)"
$ClientSlug    = Read-Host "Short slug for this client — no spaces (e.g. smithco)"
$ClientDomain  = Read-Host "Client website domain (e.g. smithco.co.uk)"
$VercelUrl     = Read-Host "Vercel deployment URL (e.g. https://smithco-evallab.vercel.app)"

Write-Host ""
Write-Host "── Supabase credentials ──" -ForegroundColor Cyan
$SupabaseUrl      = Read-Host "NEXT_PUBLIC_SUPABASE_URL"
$SupabaseAnonKey  = Read-Host "NEXT_PUBLIC_SUPABASE_ANON_KEY"
$SupabaseRoleKey  = Read-Host "SUPABASE_SERVICE_ROLE_KEY"

Write-Host ""
Write-Host "── OpenAI credentials ──" -ForegroundColor Cyan
$OpenAIKey = Read-Host "OPENAI_API_KEY"

Write-Host ""
Write-Host "── Langfuse credentials (press Enter to skip) ──" -ForegroundColor Cyan
$LangfusePublic  = Read-Host "LANGFUSE_PUBLIC_KEY"
$LangfuseSecret  = Read-Host "LANGFUSE_SECRET_KEY"
$LangfuseHost    = Read-Host "LANGFUSE_HOST (default: https://cloud.langfuse.com)"
if ([string]::IsNullOrWhiteSpace($LangfuseHost)) {
    $LangfuseHost = "https://cloud.langfuse.com"
}

Write-Host ""
Write-Host "Confirm the following:" -ForegroundColor Yellow
Write-Host "  Client name : $ClientName"
Write-Host "  Slug        : $ClientSlug"
Write-Host "  Domain      : $ClientDomain"
Write-Host "  Vercel URL  : $VercelUrl"
Write-Host ""
$Confirm = Read-Host "Proceed? (y/n)"
if ($Confirm -ne "y") {
    Write-Host "Aborted." -ForegroundColor Red
    exit 1
}

# ── 2. Branding find-and-replace ─────────────────────────────
Write-Host ""
Write-Host "Replacing branding..." -ForegroundColor Cyan

$Extensions = @("*.tsx", "*.ts", "*.css", "*.json", "*.md", "*.html", "*.js", "*.mjs")
$Replacements = @(
    @{ From = "EvalLab"; To = $ClientName },
    @{ From = "evallab"; To = $ClientSlug },
    @{ From = "AI Knowledge Base Evaluation Platform"; To = "$ClientName AI Knowledge Base" },
    @{ From = "RAG Evaluation Platform"; To = "AI Knowledge Base" },
    @{ From = "Accuracy-First AI. A scientific laboratory for Grounded RAG"; To = "Powered by $ClientName AI" },
    @{ From = "Not a chatbot — a laboratory for AI"; To = "$ClientName AI Assistant" },
    @{ From = "ai-eval-platform"; To = "$ClientSlug-evallab" }
)

$FilesChanged = 0

foreach ($ext in $Extensions) {
    $files = Get-ChildItem -Recurse -Filter $ext -ErrorAction SilentlyContinue |
             Where-Object { $_.FullName -notmatch "node_modules|\.next|\.git" }

    foreach ($file in $files) {
        $content = Get-Content $file.FullName -Raw -ErrorAction SilentlyContinue
        if ($null -eq $content) { continue }

        $original = $content
        foreach ($r in $Replacements) {
            $content = $content -replace [regex]::Escape($r.From), $r.To
        }

        if ($content -ne $original) {
            Set-Content -Path $file.FullName -Value $content -NoNewline
            Write-Host "  Updated: $($file.FullName)" -ForegroundColor Gray
            $FilesChanged++
        }
    }
}

Write-Host "  $FilesChanged file(s) updated." -ForegroundColor Green

# ── 3. Generate .env.local ───────────────────────────────────
Write-Host ""
Write-Host "Generating .env.local..." -ForegroundColor Cyan

$envContent = @"
# ============================================================
# $ClientName — EvalLab Environment Configuration
# Generated by setup-client.ps1 on $(Get-Date -Format "yyyy-MM-dd HH:mm")
# ============================================================

# Supabase
NEXT_PUBLIC_SUPABASE_URL=$SupabaseUrl
NEXT_PUBLIC_SUPABASE_ANON_KEY=$SupabaseAnonKey
SUPABASE_SERVICE_ROLE_KEY=$SupabaseRoleKey

# OpenAI
OPENAI_API_KEY=$OpenAIKey

# Langfuse observability (remove if not using)
LANGFUSE_PUBLIC_KEY=$LangfusePublic
LANGFUSE_SECRET_KEY=$LangfuseSecret
LANGFUSE_HOST=$LangfuseHost
LANGFUSE_BASEURL=$LangfuseHost
"@

Set-Content -Path ".env.local" -Value $envContent
Write-Host "  .env.local written." -ForegroundColor Green

# ── 4. Update Supabase Auth redirect URL reminder ────────────
Write-Host ""
Write-Host "=================================================" -ForegroundColor Yellow
Write-Host "  MANUAL STEPS REQUIRED" -ForegroundColor Yellow
Write-Host "=================================================" -ForegroundColor Yellow
Write-Host ""
Write-Host "1. SUPABASE AUTH — set these URLs:" -ForegroundColor White
Write-Host "   Site URL    : $VercelUrl" -ForegroundColor Cyan
Write-Host "   Redirect URL: $VercelUrl/auth/callback" -ForegroundColor Cyan
Write-Host "   Dashboard   : Supabase → Authentication → URL Configuration" -ForegroundColor Gray
Write-Host ""
Write-Host "2. SUPABASE SQL EDITOR — run schema.sql:" -ForegroundColor White
Write-Host "   File: supabase/schema.sql" -ForegroundColor Cyan
Write-Host "   This creates all tables, RLS policies, RPCs, and indexes." -ForegroundColor Gray
Write-Host ""
Write-Host "3. CREATE CLIENT USER in Supabase Auth:" -ForegroundColor White
Write-Host "   Authentication → Users → Add user" -ForegroundColor Cyan
Write-Host "   Send login credentials securely to client." -ForegroundColor Gray
Write-Host ""
Write-Host "4. VERCEL — add environment variables:" -ForegroundColor White
Write-Host "   Copy all values from .env.local into Vercel → Settings → Environment Variables" -ForegroundColor Cyan
Write-Host ""
Write-Host "5. DEPLOY:" -ForegroundColor White
Write-Host "   git add -A" -ForegroundColor Cyan
Write-Host "   git commit -m `"Client: $ClientName provisioning`"" -ForegroundColor Cyan
Write-Host "   git push origin main" -ForegroundColor Cyan
Write-Host ""
Write-Host "=================================================" -ForegroundColor Green
Write-Host "  Provisioning complete for: $ClientName" -ForegroundColor Green
Write-Host "=================================================" -ForegroundColor Green
Write-Host ""
